services:
  postgres:
    image: postgres:16-alpine
    container_name: cert-trainer-db
    environment:
      POSTGRES_USER: certtrainer
      POSTGRES_PASSWORD: certtrainer
      POSTGRES_DB: certtrainer
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U certtrainer']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cert-trainer-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@certtrainer.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
